from typing import Union

def compress(bytesObj: Union[bytes, bytearray, memoryview, str]) -> Union[str, bytes]: ...
def decompress(bytesObj: Union[bytes, bytearray, memoryview, str]) -> Union[str, bytes]: ...
