# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
    - main
    - test
  pull_request:
    branches: 
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out repository
      uses: actions/checkout@v2
    - name: install python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
        architecture: x64 
    - name: mypy
      run: pip install pytest-mypy
      
    - name: pytest-cov
      uses: lpenz/ghaction-pytest-cov@v1
      
    - name: Black formatter
      uses: lgeiger/black-action@master
      
    - name: coverage
      uses: orgoro/coverage@v2.1
      with:
        coverageFile: coverage.xml
